Add alerter for IRIS IRP system
jertel/elastalert2 pull request #1301
Opened 2023-10-23 14:38 UTC by malinkinsa

## Description

Added a new alerter type for the ability to create alerts and cases in the IRIS IRP system.

## Checklist

- [ x ] I have reviewed the [contributing guidelines](https://github.com/jertel/elastalert2/blob/master/CONTRIBUTING.md).
- [ x ] I have included unit tests for my changes or additions.
- [ x ] I have successfully run `make test-docker` with my changes.
- [ x ] I have manually tested all relevant modes of the change in this PR.
- [ x ] I have updated the [documentation](https://elastalert2.readthedocs.io).
- [ x ] I have updated the [changelog](https://github.com/jertel/elastalert2/blob/master/CHANGELOG.md).

2023-10-24 13:14 UTC, jertel requested changes
Thanks for this useful contribution! I added a few comments to this review. I'll enable the automated tests in the meantime.

2023-10-24 13:14 UTC, jertel commented on docs/source/ruletypes.rst
> +``iris_alert_context``:
This needs a description. Make sure the expected type is clarified. I could see someone putting a string here which might cause some unexpected behavior with the new alerting code.

2023-10-24 13:14 UTC, jertel commented on elastalert/loaders.py
> +# import elastalert.alerters.lark
Why is this lark import disabled?

2023-10-24 13:14 UTC, jertel commented on elastalert/loaders.py
> +        # 'lark': elastalert.alerters.lark.LarkAlerter,
Same here with Lark being disabled.

2023-10-24 13:16 UTC, jertel commented
The reason the automation failed is due to the linter finding some white space violations in your new code/tests.

2023-10-24 14:55 UTC, malinkinsa commented
I see a problem in the tests, so I'm taking a look.

2023-10-24 15:07 UTC, jertel commented on docs/source/ruletypes.rst
> +``iris_alert_context``:
I had intended this comment to be for the `iris_alert_context` line but GitHub expanded it to cover additional lines. So it's really iris_alert_context which needs a description. Sorry for the confusion.

2023-10-24 15:32 UTC, malinkinsa commented
> The reason the automation failed is due to the linter finding some white space violations in your new code/tests.

Fixed

2023-10-24 20:56 UTC, jertel reviewed
This is looking good to me. I'll leave it open for a little while to let others offer their feedback.

2023-10-27 10:54 UTC, jertel approved these changes

2023-10-27 10:54 UTC, merged

2023-12-28 11:59 UTC, Areopagit commented
IRIS alert context does not work correctly.
iris_alert_context:
hostname: host.hostname
domain: user.domain
ip: host.ip
user: winlog.event_data.TargetUserName
timestamp: event.created
message: message
log: winlog
tags: tags

hostname, domain, ip, user and timestamp dont work. This fields in IRIS are empty.
But field from a single word (message, winlog, tags) - OK!

The dot somehow gets in the way...

Please, help. All fields of Windows logs contain dot.