#110: Replace yaml loader with one that supports env value substitutions.
jertel/elastalert2 pull request #149
Opened 2021-05-10 17:04 UTC by archfz

2021-05-10 17:05 UTC, archfz commented
This is my first change in python language, so advise if anything seems off.

2021-05-11 19:34 UTC, jertel requested changes

2021-05-11 20:02 UTC, archfz commented on Makefile
> +%:
This is required unfortunately to be able to pass arguments to make. But i think it's a small price to pay for a good feature. The only thing is that commands that do not exist won't print an error.

2021-05-11 20:03 UTC, archfz commented on elastalert/alerts.py
> -from staticconf.loader import yaml_loader
I think we can remove.

2021-05-12 11:03 UTC, jertel commented on elastalert/alerts.py
> -from staticconf.loader import yaml_loader
@nsano-rururu Do you concur? You've spent a lot of time reviewing those dependencies so your opinion is appreciated.

2021-05-12 11:11 UTC, nsano-rururu commented on elastalert/alerts.py
> -from staticconf.loader import yaml_loader
@jertel  Yes. is consent.

2021-05-13 07:03 UTC, archfz commented on elastalert/alerts.py
> -from staticconf.loader import yaml_loader
@jertel removed

2021-05-13 11:52 UTC, jertel approved these changes

2021-05-13 12:14 UTC, merged