Tidy example files into a single folder
jertel/elastalert2 pull request #271
Opened 2021-06-13 06:52 UTC by ferozsalam

This reduces clutter in the root directory and gives us a place to
put all sample files in the future.

Also updates the documentation to point to the new file locations.

2021-06-13 12:58 UTC, jertel requested changes
Nice work! Found one small typo.

2021-06-13 12:58 UTC, jertel commented on docs/source/ruletypes.rst
> +For an example configuration file using this rule type, look at ``example/rules/example_frequency.yaml``.
Typo: `example/` should be `examples/`

2021-06-14 20:18 UTC, ferozsalam commented
Thanks @jertel - now fixed.

2021-06-14 20:52 UTC, jertel approved these changes

2021-06-14 20:53 UTC, merged