Make http post alerter more flexible
jertel/elastalert2 pull request #530
Opened 2021-11-01 12:18 UTC by lepouletsuisse

## Description

Add a new alerter `HTTP Post 2` which is a more flexible version of the `HTTP Post` alerter.
This version allow remove the difference between `http_post_payload` and `http_post_payload_static` to privileged only one field `http_post_payload` which allow to use Jinja2 templating to inject fields in a HTTP Post body.  
The Jinja templating works for the keys and also the values, providing total flexibility for the users to send HTTP request with any format using the fields of the matches.  

This PR resolve (at least partially):
- https://github.com/jertel/elastalert2/issues/165

## Checklist

- [x] I have reviewed the [contributing guidelines](https://github.com/jertel/elastalert2/blob/master/CONTRIBUTING.md).
- [x] I have included unit tests for my changes or additions.
- [x] I have successfully run `make test-docker` with my changes.
- [x] I have manually tested all relevant modes of the change in this PR.
- [x] I have updated the [documentation](https://elastalert2.readthedocs.io).
- [x] I have updated the [changelog](https://github.com/jertel/elastalert2/blob/master/CHANGELOG.md).

## Questions or Comments

- I ran multiple tests for different scenarios (clash with fields, nested fields) and it seems to work pretty fine. However, I never used the HTTP Post alerter before and I'm not aware of specific limitations that could block using Jinja 2.
- I created a new alerter so it doesn't break the old alerter `HTTP Post` and doesn't require a major version change.
- While running `make test-docker`, 1 test failed named `TencentSMS` because the SecretId is not set. I'm pretty sure this is not my code that make this test fail so I considered the test-docker run successfully.

2021-11-01 14:28 UTC, nsano-rururu commented
I don't seem to fix loaders.py

2021-11-01 14:29 UTC, nsano-rururu commented
How to write changelog is different from other people. Please correct.

2021-11-01 14:32 UTC, nsano-rururu commented
Does this really work?

2021-11-01 14:37 UTC, nsano-rururu commented
It looks like HTTPPost2Alerter isn't called from anywhere. If you specify alert: post, it will be called HTTP Post Alerter as it is.

2021-11-01 14:40 UTC, nsano-rururu commented
If you want to keep the HTTPPostAlerter, you may use the old one and the new one at the same time. If so, shouldn't the setting name be http_post2_ setting name at the beginning so that it doesn't collide?

2021-11-01 15:26 UTC, lepouletsuisse commented
> I don't seem to fix loaders.py

As I said, it `partially` fixed the issue. My purpose is not to fix the loader, only to create a more flexible HTTP alerter.

> It looks like HTTPPost2Alerter isn't called from anywhere. If you specify alert: post, it will be called HTTP Post Alerter as it is.

Yeah, my bad. I'm not really familiar with this code, so I forgot to add the `post2` to the `loaders.py`. It's fixed now.

> If you want to keep the HTTPPostAlerter, you may use the old one and the new one at the same time. If so, shouldn't the setting name be http_post2_ setting name at the beginning so that it doesn't collide?

Yes totally, thanks for pointing it out! I'm fixing this in a new commit

2021-11-01 15:37 UTC, nsano-rururu commented
I think you should add the validation check setting to schema.yaml. There is a description of HTTP POST settings in 440 to 445. When you run the rule, jsonschema can check the settings in schema.yaml and check the data type if there is a key, and if they are different, you can raise an exception to prevent the rule from running.
https://github.com/jertel/elastalert2/blob/master/elastalert/schema.yaml#L440

2021-11-01 15:39 UTC, nsano-rururu commented
@jertel 

Is there anything else you care about?

2021-11-01 16:30 UTC, jertel requested changes

2021-11-01 16:30 UTC, jertel commented on elastalert/alerters/httppost2.py
> +                    raise EAException("Error posting HTTP Post alert: %s" % e)
Might be a good idea to add a "2" to this text and the log line below, so it's clear when someone asks for support which alerter they're using.

2021-11-02 11:04 UTC, jertel approved these changes

2021-11-02 11:04 UTC, merged