Bearer token authorization.
jertel/elastalert2 pull request #85
Opened 2021-04-24 23:24 UTC by StribPav

2021-04-25 09:34 UTC, nsano-rururu commented
@StribPav 

I don't need it because "'tzlocal <3.0'," has already been added to setup.py.

2021-04-25 14:35 UTC, jertel requested changes

2021-04-25 14:35 UTC, jertel commented on setup.py
> +        'tzlocal<3.0',
This line needs to be removed since it already exists at the bottom of this list.

2021-04-26 16:43 UTC, jertel approved these changes

2021-04-26 16:48 UTC, merged