Task/show warn false
jertel/elastalert2 pull request #87
Opened 2021-04-26 05:40 UTC by alvarolmedo

2021-04-26 06:24 UTC, nsano-rururu commented
@alvarolmedo

The current elastalert2 has "elasticsearch>=7.0.0,<8.0.0", so it seems that you don't need to modify requirements.txt and setup.py.

2021-04-26 23:37 UTC, jertel requested changes

2021-04-26 23:37 UTC, jertel commented on requirements.txt
>  envparse>=0.2.0
If you can revert the es lib upgrade (see #90 for why this is needed) we can get this merged in. If there is any applicable doc updates that might be helpful as well.

2021-04-27 16:19 UTC, jertel commented on requirements.txt
>  envparse>=0.2.0
Nevermind, I was able to revert it.

2021-04-27 16:28 UTC, merged

2021-04-28 16:13 UTC, alvarolmedo commented
Sorry to be late, thank you. :)